services:
  - type: web
    name: gst-billing
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: GST-Billing
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql

databases:
  - name: gst-billing-db
    databaseName: gst_billing
    user: gst_user
    plan: free
